export const products = [
  {
    _id: "A",
    title: "Nexon EV",
    price: 11110,
    inStock: true,
    description: `The electric version of the Nexon was revealed on 19 December 2019. The Nexon EV uses components from Tata Motors' electric vehicle technology brand Ziptron. The electric motor produces 94.7 kW (127 hp; 129 PS) and 245 N⋅m (181 lbf⋅ft) of torque and 0 - 100 under 9.9 seconds. It has a 30.2 kWh battery with an ARAI rated range of up to 312 km.
The battery can be fully charged in under 8 hours using a complimentary AC charger. It can also be charged using a 15-ampere power cable that can be used at any place with the necessary power socket. DC 25 kW fast charging can be used to charge the battery from 0 to 80% in 1 hour.
Tata started a subscription plan for the Nexon EV in August 2020. It was reported that Nexon EV was the best-selling electric vehicle in India in 2020.`,
    categoryName: "ev",
    manufacturedBy: "Tata",
    image: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/42611/nexon-ev-exterior-front-view.jpeg?q=75",
    rating: 5,
  },
  {
    _id: "B",
    title: "Mahindra Scorpio",
    price: 11115,
    inStock: true,
    description: `The Mahindra Scorpio is a mid-size SUV manufactured by the Indian automaker Mahindra & Mahindra since 2002. It was Mahindra's first model to be built for the global market.
The Scorpio was conceptualized and designed by the in-house integrated design and manufacturing team of Mahindra & Mahindra. The car has been the recipient of three Indian awards, including the "Car of the Year" award from Business Standard Motoring as well as the "Best SUV of the Year" and the "Best Car of the Year" awards, both from BBC World's Wheels.`,
    categoryName: "petrol",
    manufacturedBy: "Mahindra",
    image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/31883/scorpio-exterior-right-front-three-quarter-2.jpeg?q=75",
    rating: 3,
  },
  {
    _id: "C",
    title: "Creta",
    price: 10900,
    inStock: true,
    description: `The Hyundai Creta, also known as Hyundai ix25 in China, is an automobile produced by Hyundai since 2014 mainly for emerging markets, particularly BRICS. A subcompact crossover SUV, it is positioned below the Tucson in Hyundai's SUV line-up.
The first-generation model debuted as a near-production concept car in China in April 2014, while the second generation was first introduced in 2019. The second-generation model was also available in a longer derivative with three-row seating, which is known as the Hyundai Alcazar, Creta Grand or Grand Creta. The vehicle has been manufactured in China, India, Russia, Brazil, and Indonesia.`,
    categoryName: "diesel",
    manufacturedBy: "Hyundai",
    image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/41564/hyundai-creta-right-front-three-quarter9.jpeg?q=75&wm=1",
    rating: 5,
  },
  {
    _id: "D",
    title: "Mahindra Thar",
    price: 10650,
    inStock: true,
    description: `The vehicle was launched in the Indian market on October 4, 2010 to fill the void left by its predecessor, the Mahindra MM540. The Thar has been voted one of the top-10 SUVs available in the Indian market. Three variants - DI 2WD, DI 4WD, and CRDe, are available with soft-top versions. The Thar also comes with a seven-seater option, though it can be converted into a two-seater.`,
    categoryName: "diesel",
    manufacturedBy: "Mahindra",
    image: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/40087/thar-exterior-left-rear-three-quarter.jpeg?q=75",
    rating: 4,
  },
  {
    _id: "E",
    title: "Mahindra XUV700",
    price: 12790,
    inStock: true,
    description: `The vehicle was introduced on 14 August 2021. The XUV700 was originally designed as the second-generation XUV500, however Mahindra decided to reposition the model nomenclature due to its plan of expanding its SUV portfolio. It is their first model to use the new Mahindra logo, which is reserved for their SUV products.`,
    categoryName: "diesel",
    manufacturedBy: "Mahindra",
    image: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/42355/xuv700-exterior-front-view-2.jpeg?isig=0&q=75",
    rating: 4,
  },
  {
    _id: "F",
    title: "Toyota Fortuner",
    price: 11870,
    inStock: true,
    description: `The Toyota Fortuner, also known as the Toyota SW4, is a mid-size SUV manufactured by the Japanese automaker Toyota since 2004. Built on the Hilux pickup truck platform, it features two/three rows of seats and is available in either rear-wheel drive or four-wheel drive configuration. It is a part of Toyota's IMV project for emerging markets, which also includes the Hilux and the Innova.`,
    categoryName: "diesel",
    manufacturedBy: "Toyota",
    image: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/44709/fortuner-exterior-left-front-three-quarter.jpeg?q=75",
    rating: 1,
  },
  {
    _id: "G",
    title: "Nexon",
    price: 11150,
    inStock: true,
    description: `The Nexon made its debut as a prototype exhibited at the Auto Expo 2014. The final model was presented in February 2016. The Nexon is based on the revised Tata X1 platform debuted in 1998 with the Indica model and adopted by other Indian brand cars.`,
    categoryName: "petrol",
    manufacturedBy: "Tata",
    image: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/41645/nexon-exterior-left-front-three-quarter-2.jpeg?q=75",
    rating: 3,
  },
  {
    _id: "H",
    title: "Land Rover",
    price: 10290,
    inStock: true,
    description: `Land Rover is a British brand of predominantly four-wheel drive, off-road capable vehicles, owned by multinational car manufacturer Jaguar Land Rover (JLR), since 2008 a subsidiary of India's Tata Motors. JLR currently builds Land Rovers in Brazil, China, India, Slovakia, and the United Kingdom.`,
    categoryName: "diesel",
    manufacturedBy: "Tata",
    image: "https://imgd.aeplcdn.com/1056x594/cw/ec/28085/Land-Rover-Range-Rover-Velar-Exterior-114227.jpg?wm=1&q=75",
    rating: 5,
  },
  {
    _id: "I",
    title: "Innova Crysta",
    price: 12980,
    inStock: false,
    description: `The Toyota Innova is a car manufactured by the Japanese carmaker Toyota since 2004. It is a compact MPV and mainly sold with three-row seating. It entered production in Indonesia under supervision by Toyota-Astra Motor in 2004 and has been manufactured in other emerging countries as well.`,
    categoryName: "petrol",
    manufacturedBy: "Toyota",
    image: "https://imgd.aeplcdn.com/664x415/n/cw/ec/51435/innova-crysta-exterior-left-front-three-quarter.jpeg?q=75",
    rating: 3,
  },
  {
    _id: "J",
    title: "Kia Carnival",
    price: 13480,
    inStock: true,
    description: `The Kia Carnival is a minivan manufactured by Kia since 1998. It is marketed globally under various nameplates — prominently as the Kia Sedona — which is now unused in favor of the Carnival.`,
    categoryName: "ev",
    manufacturedBy: "Kia",
    image: "https://imgd.aeplcdn.com/664x415/n/cw/ec/41205/carnival-exterior-left-front-three-quarter.jpeg?q=75",
    rating: 1,
  },
  {
    _id: "K",
    title: "BMW M5",
    price: 15500,
    inStock: false,
    description: `The BMW 5 Series is an executive car manufactured and marketed by BMW since 1972, succeeding the New Class Sedans, and currently in its seventh generation.`,
    categoryName: "petrol",
    manufacturedBy: "BMW",
    image: "https://imgd.aeplcdn.com/664x415/n/cw/ec/14881/m5-exterior-right-front-three-quarter-9.jpeg?q=75",
    rating: 5,
  },
  {
    _id: "L",
    title: "Audi Q7",
    price: 15200,
    inStock: true,
    description: `The Audi Q7 is a full-size luxury crossover SUV made by the German manufacturer Audi, unveiled in September 2005.`,
    categoryName: "ev",
    manufacturedBy: "Audi",
    image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/44717/audi-q7-right-front-three-quarter6.jpeg?q=75",
    rating: 4,
  },
];
