export const products = [
  
    {
      _id: "W6",
      title: "Wrap Skirt",
      price: 1299,
      inStock: false,
      description: `Chic wrap skirt made from cotton-linen blend fabric. Features a tie closure at the side and a flowy silhouette. Ideal for casual and semi-formal occasions.`,
      categoryName: "skirts",
      manufacturedBy: "Boho Vibes",
      image: "https://tamarindchutney.in/cdn/shop/files/TamarindChutney_MeherWrapSkirt_Green2_1080x.jpg?v=1716191641",
      rating: 4.6,
    },
    {
      _id: "W7",
      title: "Anarkali Kurta",
      price: 2199,
      inStock: true,
      description: `Elegant Anarkali-style kurta with golden prints. Made from fine Chanderi cotton, it features a mandarin collar and three-quarter sleeves. Perfect for traditional and festive occasions.`,
      categoryName: "kurtas",
      manufacturedBy: "Ethnic Grace",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcWLm8USB6mLJRjf1nNiomXtc0w4u5l_GftQ&s",
      rating: 4.7,
    },
    {
      _id: "W8",
      title: "Formal Blazer",
      price: 2999,
      inStock: true,
      description: `Tailored formal blazer with a single-breasted design. Made from premium polyester blend fabric, this blazer is a perfect choice for business meetings and professional settings.`,
      categoryName: "blazers",
      manufacturedBy: "PowerWear",
      image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/blazer/5/x/h/s-blazer-black-blue-ronin-original-imag6y32hhxkkjqm-bb.jpeg?q=90&crop=false",
      rating: 4.4,
    },
    {
      _id: "W9",
      title: "Cotton Palazzo Pants",
      price: 999,
      inStock: true,
      description: `Wide-leg cotton palazzo pants designed for all-day comfort. Features an elastic waistband and side pockets. Ideal for pairing with kurtas or casual tops.`,
      categoryName: "bottoms",
      manufacturedBy: "Comfort & Style",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAzoXgSpUoBq02BDCnJ2_UpD8V6XJOlpLivg&s",
      rating: 4.5,
    },
    {
      _id: "W10",
      title: "Winter Coat",
      price: 3499,
      inStock: true,
      description: `Warm and stylish winter coat with a double-breasted closure and a waist belt. Made from wool-blend fabric to keep you cozy in cold weather. Available in neutral colors.`,
      categoryName: "coats",
      manufacturedBy: "Winter Luxe",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiiD2fLzUhGqQxrpfeXrH-o9WmRj29XNNhmA&s",
      rating: 4.6,
    },
   
    {
      _id: "W12",
      title: "Embroidered Lehenga",
      price: 8999,
      inStock: false,
      description: `Exquisite lehenga with intricate embroidery and beadwork. Comes with a matching blouse and dupatta. Perfect for weddings and grand celebrations.`,
      categoryName: "ethnic",
      manufacturedBy: "Royal Couture",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4_Lg6HqQKpapwqPoAI-dyZwf5k8cIA23NKA&s",
      rating: 4.8,
    },
    {
      _id: "W13",
      title: "Ribbed Knit Sweater",
      price: 1299,
      inStock: true,
      description: `Cozy ribbed knit sweater made from soft acrylic yarn. Features a turtleneck and a relaxed fit, perfect for layering during winter.`,
      categoryName: "sweaters",
      manufacturedBy: "Winter Bliss",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQDvkfgXC1S0YCu_dwxDRxY5Qjo_6OB_rZ9w&s",
      rating: 4.5,
    },
    {
      _id: "W14",
      title: "Printed Scarf",
      price: 499,
      inStock: true,
      description: `Lightweight printed scarf made from viscose fabric. Adds a touch of elegance to any outfit. Available in a variety of vibrant prints.`,
      categoryName: "accessories",
      manufacturedBy: "Fashion Flair",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC2tXwvFsk7T0OWok2I2cy4VZ4kvc3xFm56g&s",
      rating: 4.3,
    },
    {
      _id: "W15",
      title: "Sheath Dress",
      price: 2299,
      inStock: true,
      description: `Sophisticated sheath dress designed for formal and evening wear. Features a boat neckline and a concealed zipper at the back. Made from stretchable fabric for a perfect fit.`,
      categoryName: "dresses",
      manufacturedBy: "Elegant Curve",
      image: "https://rukminim2.flixcart.com/image/850/1000/kthjy4w0/dress/p/e/f/m-sfdrss10298-sassafras-original-imag6tbmg63t268c.jpeg?q=90&crop=false",
      rating: 4.6,
    },
    {
      _id: "W16",
      title: "Denim Jacket",
      price: 1899,
      inStock: true,
      description: `Classic denim jacket with a button-front closure and flap pockets. Made from durable denim fabric. Ideal for layering over casual outfits.`,
      categoryName: "jackets",
      manufacturedBy: "Street Style",
      image: "https://assets.vogue.in/photos/620e40b5ecc68b9d65d3896c/master/pass/Alia%20Bhatt%20in%20denim.jpg",
      rating: 4.4,
    },
    {
      _id: "W17",
      title: "Sleeveless Tank Top",
      price: 499,
      inStock: true,
      description: `Basic sleeveless tank top made from soft and breathable cotton fabric. Perfect for layering or wearing on its own during hot weather.`,
      categoryName: "tops",
      manufacturedBy: "Comfort Basics",
      image: "https://assets.ajio.com/medias/sys_master/root/20230624/a0v6/64961da6a9b42d15c9d228de/-473Wx593H-465155459-black-MODEL3.jpg",
      rating: 4.2,
    },
    {
      _id: "W18",
      title: "Linen Trousers",
      price: 1599,
      inStock: true,
      description: `Relaxed-fit linen trousers with an elasticized waistband and drawstring. Ideal for casual and semi-formal wear. Available in earthy tones.`,
      categoryName: "bottoms",
      manufacturedBy: "Earthy Chic",
      image: "https://assets.ajio.com/medias/sys_master/root/20240508/Wl8e/663b750805ac7d77bb48dc98/-473Wx593H-442528412-beige-MODEL.jpg",
      rating: 4.5,
    },
    {
      _id: "W19",
      title: "Evening Gown",
      price: 4999,
      inStock: true,
      description: `Graceful evening gown with an off-shoulder design and a flared hemline. Made from satin fabric with subtle embellishments. Perfect for formal events.`,
      categoryName: "gowns",
      manufacturedBy: "Glamour Attire",
      image: "https://clothsvilla.com/cdn/shop/products/BlackPromDressesV-NeckPuffySleevesA-LineEveningGownforWedding_1_782x.jpg?v=1697220843",
      rating: 4.9,
    },
    {
      _id: "W20",
      title: "Boho Printed Tunic",
      price: 1299,
      inStock: true,
      description: `Trendy boho-style printed tunic with tassel details and a relaxed fit. Made from lightweight cotton fabric. Pair with leggings or jeans for a chic look.`,
      categoryName: "tunics",
      manufacturedBy: "Boho Charm",
      image: "https://images.meesho.com/images/products/423297354/flxis_512.webp",
      rating: 4.6,
    }
  ]
